import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import NavBar from "@/components/NavBar";
import "./globals.css";

const spaceGortesk = Space_Grotesk({
  variable: "--space-gortesk",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Priyanshu Soni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGortesk.variable} antialiased `}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
